In [2]:
import pickle
from pathlib import Path

import pandas as pd
import numpy as np
import seaborn.objects as so
from seaborn import axes_style

from IPython.display import display

In [7]:
insertion_dir = Path("/home/fisch872/mat/projects/Laura-SB-Analysis/publication/output/2020_SB/results-insertions")
treatment = "S"

In [8]:
insert_list = []
for file in insertion_dir.iterdir():
    tmp_df = pd.read_csv(file, sep="\t")
    tmp_meta = file.name.split(".")[0].split("-")
    # TODO: this needs to be cleaned up and a better standard implemented.
    # maybe a standardized meta-data file?
    if len(tmp_meta) == 3:  # 2020 SB
        tmp_df["treatment"] = tmp_meta[2]
        tmp_df["sampleID"] = tmp_meta[1]
        tmp_df["cell_type"] = tmp_meta[0]
    elif len(tmp_meta) == 2:  # 2023 SB
        tmp_df["treatment"] = tmp_meta[0]
        tmp_df["sampleID"] = tmp_meta[1]
        
    tmp_df["sample_sub_id"] = range(len(tmp_df))
    insert_list.append(tmp_df)
inserts_df = pd.concat(insert_list, ignore_index=True)
display(inserts_df)

,chr,pos,strand,ref_length,query_length,read_length,mapping_quality,read_name,TA_location,read_first_last,ref_first_last,tpn_promoter_orient,library,treatment,sampleID,cell_type,sample_sub_id
0,chr1,53601100,+,135,147,147,14,K00274:76:HHHM2BBXX:8:2128:16224:28446,none,GATAAATTTG-AGGTCCTAGA,GGAGcAGTTG-AGGTCCTAGA,-,IRL,LT,32_2,EL4,0
1,chr1,68392291,+,70,71,71,42,K00274:76:HHHM2BBXX:8:1108:29193:25984,first,TATATATAGA-GCCTCATTTT,TATATATAGA-TGCCTCATTT,+,IRR,LT,32_2,EL4,1
2,chr1,68392291,+,71,71,71,42,K00274:76:HHHM2BBXX:8:1227:5974:17685,first,TATATATAGA-GCCTCATTTC,TATATATAGA-GCCTCATTTC,+,IRR,LT,32_2,EL4,2
3,chr1,68392291,+,68,68,68,28,K00274:76:HHHM2BBXX:8:2108:24870:26265,first,TATATATAGA-TCTGCCTCAT,TATATATAGA-TCTGCCTCAT,+,IRR,LT,32_2,EL4,3
4,chr1,68392291,+,67,67,67,28,K00274:76:HHHM2BBXX:8:2202:3133:47084,first,TATATATAGA-TTCTGCCTCA,TATATATAGA-TTCTGCCTCA,+,IRR,LT,32_2,EL4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242346,chr6,53233280,-,43,148,148,22,K00275:54:HHHJTBBXX:8:1124:3407:34477,none,GATTAAATGT-CTGCTTGAAA,ATTAAGATAT-AATTCCTGAC,-,IRR,LT,456_4,B16,6
242347,chr6,53233280,-,43,72,72,22,K00275:54:HHHJTBBXX:8:1221:22445:26986,none,AGGATTAAAT-GCGGAGCCCT,ATTAAGATAT-AATTCCTGAC,-,IRR,LT,456_4,B16,7
242348,chr6,86910729,+,102,146,146,41,K00274:188:HW2KTBBXX:5:2125:20557:21852,none,TTTTGTAAAC-CACCAGTGCT,TAACTAACAA-CACCAGTGCT,+,IRR,RT,46_2,EL4,0
242349,chr6,86910822,-,108,148,148,41,K00274:188:HW2KTBBXX:5:1101:6948:19619,none,GTGGATTAAA-ATAGTGAGTC,ACCAGTGCTG-ACAATTCCTG,+,IRL,RT,46_2,EL4,1
242350,chr6,86910867,-,63,148,148,22,K00274:188:HW2KTBBXX:5:1227:5761:14713,none,AGGATTAAAT-CCACGAGACC,CCCACCAGCT-ACAATTCCTG,+,IRL,RT,46_2,EL4,2

In [4]:
bed_col = [
    "chrom",
    "chromStart",  # 0-index based
    "chromEnd",
    "name",
    "score",  #  A score between 0 and 1000
    "strand",
    "thickStart",  # set to chromStart
    "thickEnd",  # set to chromStart
    "itemRGB",
    "blockCount",
    "blockSizes",
    "blockStart"
]

In [38]:
out2_df = pd.DataFrame(inserts_df["chr"])
out2_df.columns = ["chrom"]
out2_df["chromStart"] = inserts_df["pos"]
out2_df["chromEnd"] = inserts_df["pos"]
out2_df["name"] = inserts_df["treatment"]  # "test"  # inserts_df["sampleID"]
out2_df["score"] = 1000
out2_df["strand"] = inserts_df["strand"]
out2_df["thickStart"] = out2_df["chromStart"]
out2_df["thickEnd"] = out2_df["chromStart"]
out2_df["itemRGB"] = "255,0,0"
out2_df["blockCount"] = 0
out2_df["blockSizes"] = ""
out2_df["blockStart"] = ""

out2_df = out2_df[out2_df["name"] == treatment]
out2_df.to_csv(insertion_dir.parent / f"{treatment}.bed", sep="\t", index=False, header=False)
out2_df

,chrom,chromStart,chromEnd,name,score,strand,thickStart,thickEnd,itemRGB,blockCount,blockSizes,blockStart
1620,chr11,113830728,113830728,RT,1000,+,113830728,113830728,"255,0,0",0,,
1621,chr11,113830728,113830728,RT,1000,+,113830728,113830728,"255,0,0",0,,
1622,chr14,3052299,3052299,RT,1000,-,3052299,3052299,"255,0,0",0,,
1623,chr14,14299784,14299784,RT,1000,+,14299784,14299784,"255,0,0",0,,
1624,chr14,59037734,59037734,RT,1000,+,59037734,59037734,"255,0,0",0,,
...,...,...,...,...,...,...,...,...,...,...,...,...
242290,chrY,47921473,47921473,RT,1000,-,47921473,47921473,"255,0,0",0,,
242291,chrY,60282889,60282889,RT,1000,+,60282889,60282889,"255,0,0",0,,
242348,chr6,86910729,86910729,RT,1000,+,86910729,86910729,"255,0,0",0,,
242349,chr6,86910822,86910822,RT,1000,-,86910822,86910822,"255,0,0",0,,
242350,chr6,86910867,86910867,RT,1000,-,86910867,86910867,"255,0,0",0,,